version: '3.8'

services:
  nginx:
      build:
        context: .
        dockerfile: ./nginx-frontend/Dockerfile
      depends_on:
        - country
      expose:
        - "80"
      environment:
        - VIRTUAL_HOST=gtc.xaidemo.de
        - VIRTUAL_PORT=80
        - LETSENCRYPT_HOST=gtc.xaidemo.de
        - LETSENCRYPT_EMAIL=xai.demonstrator@gmail.com
      restart: always

  country:
    image: ghcr.io/xai-demonstrator/guess-the-country-service:latest
    depends_on:
      - jaeger
      - collector
    expose:
      - "8000"
    environment:
      - GOOGLE_MAPS_API_TOKEN=${STREETVIEW_API_KEY}
      - BATCH_SIZE=${BATCH_SIZE}
      - ROOT_PATH=/api/country
      - SERVICE_NAME=country-service
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger
      - COLLECTOR_URL=http://collector:8000
      - EXPERIMENT=1

  study:
    build: ./gtc-study-backend
    depends_on:
      - jaeger
      - couchdb
    expose:
      - "8000"
    environment:
      - SERVICE_NAME=study-backend-service
      - ROOT_PATH=/api/country
      - DB_USER=${COUCHDB_USER}
      - DB_PASSWORD=${COUCHDB_PASSWORD}
      - DB_HOST=couchdb
      - DB_PORT=5984
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger
    volumes:
      - ./gtc-study-backend/images:/backend/images

  jaeger:
    image: jaegertracing/all-in-one
    expose:
      - "6831"
    ports:
      - "16686:16686"
    restart: always

  couchdb:
    build: ./database
    expose:
      - "5984"
    ports:
      - "8001:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
        - ./../../../dbdata:/opt/couchdb/data

  collector:
    image: ghcr.io/xai-demonstrator/data-collector:latest
    depends_on:
      - couchdb
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=couchdb
      - DB_PORT=5984
      - DB_USER=${COUCHDB_USER}
      - DB_PASSWORD=${COUCHDB_PASSWORD}
      - SERVICE_NAME=data-collector
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger

  proxy:
    image: ghcr.io/xai-demonstrator/experiment-proxy:latest
    depends_on:
      - collector
      - country
    expose:
      - "8000"
    environment:
      - BACKEND_URL=http://study:8000
      - BACKEND_SERVICE=study-backend-service
      - COLLECTOR_URL=http://collector:8000
      - SERVICE_NAME=experiment-proxy
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger

networks:
  default:
    external:
      name: nginx-proxy
