name: Move Sentiment Service to CloudRun

on:
  push:
    branches:
      - master


env:
  PROJECT_ID: ${{ secrets.GCP_TEST_PROJECT_ID }}
  SERVICE: review-sentiment
  REGION: europe-west3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_TEST_SA_KEY }}
        export_default_credentials: true  # Set to true to authenticate the Cloud Run action

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker pull ghcr.io/xai-demonstrator/review-sentiment-service:latest
        docker tag ghcr.io/xai-demonstrator/review-sentiment-service gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
  
    - name: Deploy to Cloud Run
      run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} \
            --platform managed \
            --port 8000 \
            --memory "4Gi" \
            --allow-unauthenticated \

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
